# Generated by Django 5.1.2 on 2024-10-11 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('ZipCode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(blank=True, max_length=8, null=True)),
                ('passportNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(max_length=100)),
                ('familyName', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=100)),
                ('nbStars', models.CharField(choices=[('3', 'Three Stars'), ('4', 'Four Stars'), ('5', 'Five Stars')], max_length=2)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.address')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('STD', 'standard'), ('DLX', 'deluxe'), ('STE', 'suite'), ('OTH', 'other')], default='STD', max_length=10)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationDate', models.DateTimeField(auto_now_add=True)),
                ('inDate', models.DateTimeField(auto_now_add=True)),
                ('outDate', models.DateTimeField(auto_now_add=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room')),
            ],
            options={
                'ordering': ['inDate'],
                'unique_together': {('room', 'inDate')},
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='reservations',
            field=models.ManyToManyField(through='hotel_app.Reservation', to='hotel_app.room'),
        ),
    ]
