# Generated by Django 5.1.2 on 2024-10-11 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SAL', 'Salaries'), ('UTL', 'utilities'), ('MTN', 'maintenance')], max_length=10)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('room_expense', models.ManyToManyField(to='hotel_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash payment'), ('CARD', 'Credit card payment'), ('CHECK', 'Check payment')], default='CASH', max_length=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.reservation')),
            ],
        ),
    ]
